services:
  - type: web
<<<<<<< HEAD
    name: labelqcchecker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
=======
    name: label-qc-checker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
>>>>>>> 018d8f107f87750f6fb7eec948efb60c62d2e72e
